config/routes.rb
Rails.application.routes.draw do
  root 'visits#new'

  get 'visits/:id' => 'visits#show', as: :visit
  get 'visits' => 'visits#index', as: :visits
  post 'visit' => 'visits#create'

  get 'users/:id' => 'users#show', as: :user

  get 'sign_up' => 'users#new', as: :sign_up
  post 'sign_up' => 'users#create', as: :users
  get 'users/:id/edit' => 'users#edit'
  patch 'users/:id' => 'users#update'

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy', as: :sign_out

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  has_many :visits
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :visits
  has_secure_password
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :users
  belongs_to :lots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def sign_in user
    session[:user_id] = user.id
  end

  def sign_out user
    session.delete :user_id
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    user = User.find_by email: email
    if user.present? && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Something is wrong with your email or password. Try again."
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path, notice: "Later!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def new
    @current_user = User.find_by id: session[:user_id]
    @visit = Visit.new
  end

  def show
    @visit = Visit.find params[:id]
  end

  def create
    @visit = Visit.new(visit_params)
    if @visit.save
      redirect_to visit_path
    else
      render :new
    end
  end

  def visit_params
    params.require(:visit).permit(:date, :time, :building, :room)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_help.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/home/index.html.erb
<% if @current_user.present? %>
  <h1><%= @current_user.first_name %></h1>
  <div class="btn">
    <%= link_to 'Sign Out', sign_out_path, method: :delete %>
  </div>
<% else %>
  <div class="btn">
    <%= link_to 'Sign In', sign_in_path %>
  </div>
  <p>or</p>
  <div class="btn">
    <%= link_to 'Create Account', sign_up_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parkway</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Patients#edit</h1>
<p>Find me in app/views/patients/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Welcome to TMC Parkway</h1>

<%= simple_form_for @user do |u| %>
  <%= u.input :first_name, label: false, placeholder: 'First Name' %>
  <%= u.input :last_name, label: false, placeholder: 'Last Name' %>
  <%= u.input :email, label: false, placeholder: 'Email' %>
  <%= u.input :password, label: false, placeholder: 'Password' %>
  <%= u.input :password_confirmation, label: false, placeholder: 'Password Confirmation' %>
  <%= u.submit 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>

app/views/visits/new.html.erb
<% if @current_user.present? %>
  <h1><%= @current_user.first_name %></h1>
  <div class="btn">
    <%= link_to 'Sign Out', sign_out_path, method: :delete %>
  </div>
<% else %>
  <div class="btn">
    <%= link_to 'Sign In', sign_in_path %>
  </div>
  <p>or</p>
  <div class="btn">
    <%= link_to 'Create Account', sign_up_path %>
  </div>
<% end %>

app/views/visits/show.html.erb
<h1>Visits#show</h1>
<p>Find me in app/views/visits/show.html.erb</p>